config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :users, only: %i[show]
  resources :accounts, only: %i[index show]
  resources :categories, only: %i[show index]

  resources :projects, except: %i[destroy] do
    get 'search', on: :collection
  end

  namespace :admin do
    resources :projects
    resources :users
    resources :organisations
    resources :administration_offices
    resources :companies
    resources :founders
    resources :engagements
    resources :categories
    resources :resources
    resources :super_admins

    authenticate :super_admin do
      mount Sidekiq::Web, at: '/sidekiq'
    end
  end

  devise_for :super_admins, path: 'admin', controllers: {
    confirmations: 'admin/confirmations',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations',
    sessions: 'admin/sessions',
    unlocks: 'admin/unlocks'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'projects#index'
end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= boostrap_class_for(type) %> alert-dismissible" role="alert">
    <%= message %>
  </div>
<% end %>

app/views/shared/_modals.html.erb
<div id="user-profile-modal" class="modal fade" tabindex="-1" role="dialog"></div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'WE, THE CITY', root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-navbar-collapse"
    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="main-navbar-collapse">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, class: 'nav-link', method: :delete %>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path,
            { class: 'nav-link', remote: true, data: { toggle: 'modal', target: '#user-profile-modal' } } %>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <div class="dropdown show">
            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Organization
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to 'New', new_organisation_path, class: 'dropdown-item' %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>