config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :users, only: %i[show]
  resources :accounts, only: %i[index show]
  resources :categories, only: %i[show index]

  resources :projects, except: %i[destroy] do
    get 'search', on: :collection
  end

  namespace :admin do
    resources :projects
    resources :users
    resources :organisations
    resources :administration_offices
    resources :companies
    resources :founders
    resources :engagements
    resources :categories
    resources :resources
    resources :super_admins

    authenticate :super_admin do
      mount Sidekiq::Web, at: '/sidekiq'
    end
  end

  devise_for :super_admins, path: 'admin', controllers: {
    confirmations: 'admin/confirmations',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations',
    sessions: 'admin/sessions',
    unlocks: 'admin/unlocks'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'projects#index'
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  extend FriendlyId

  acts_as_paranoid
  friendly_id :name, use: :slugged
  mount_uploaders :images, ImageUploader

  geocoded_by :location
  after_validation :geocode

  has_and_belongs_to_many :categories
  has_many :founders
  has_many :members, through: :founders
  has_many :engagements
  has_many :resources, through: :engagements

  validates :name, presence: true
  validates :description, presence: true
  validates :finish_on, presence: true
  validates :location, presence: true
  validates :sort_order, numericality: { greater_than: 0, allow_nil: true }
  validates :required_budget, presence: { if: :collected_budget? }
  validates :collected_budget, presence: { if: :required_budget? }

  scope :active, -> { where(active: true) }

  def self.search(q)
    q.present? ? where('name ILIKE ? and active = true', "%#{q}%") : order(sort_order: :asc).limit(20)
  end
end

app/controllers/admin/projects_controller.rb
# frozen_string_literal: true

module Admin
  class ProjectsController < Admin::ApplicationController
    before_action :set_default_params

    def find_resource(param)
      Project.friendly.find(param)
    end

    private

    def set_default_params
      params[:order] ||= 'sort_order'
      params[:direction] ||= 'asc'
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  def index
    @projects = Project.active.order(sort_order: :asc).limit(20).decorate
  end

  def search
    @projects = Project.search(params[:q]).decorate
    render :index
  end

  def show
    @project = Project.friendly.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    render plain: params[:article].inspect
  end
end

app/views/projects/_progress_bar.html.erb
<div class="progress" style="height: 1px;">
  <div class="progress-bar bg-success" role="progressbar" style="width: <%= percent %>%;"
    aria-valuenow="<%= percent %>" aria-valuemin="0" aria-valuemax="100"></div>
</div>

app/views/projects/_project.html.erb
<% if project_counter % 3 === 0 %>
  <div class="w-100 pb-3"></div>
<% end %>

<%= link_to project, class: 'project-card card bg-dark text-white' do %>
  <%= image_tag project.default_image(:medium), class: 'card-img-top', alt: "#{project.name}" %>

  <div class="card-img-overlay">
    <% if project.budget_completed_percentage? %>
      <%= render 'projects/progress_bar', percent: project.budget_completed_percentage %>
    <% end %>

    <div class="row">
      <div class="col-6 text-truncate">
        <p class="text-left"><%= number_to_currency(project.collected_budget) %></p>
      </div>

      <div class="col-6 text-truncate">
        <p class="text-right"><%= distance_of_time_in_words_to_now(project.finish_on) %></p>
      </div>
    </div>

    <span>#<%= project.sort_order %></span>

    <h4 class="card-title">
      <%= project.name %>
    </h4>
  </div>
<% end %>

app/views/projects/_search_form.html.erb
<%= form_tag search_projects_path, method: :get do %>
  <%= text_field_tag(:q, nil, class: 'form-control form-control-lg', value: params[:q],
    placeholder: t('.input_placeholder')) %>
<% end %>

app/views/projects/index.html.erb
<div id="projects-top" class="carousel" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'homepage_top.svg', class: 'd-block w-100', alt: 'we the city' %>

      <div class="carousel-caption">
        <h1 class="text-uppercase">We, The<br />City</h1>
        <p class="text-uppercase">Accelerate your Smart City projects</p>
      </div>
    </div>
  </div>
</div>

<div class="pb-3">
  <%= render "search_form" %>
</div>

<div class="card-deck">
  <%= render @projects %>
</div>

app/views/projects/new.html.erb
<%= form_for @project, url: { action: 'create', method: :post } do |form| %>
    <div class="new-project-general-info">
      <div class="form-group new-project-cover">
        <!--TO BE IMPLEMENTED: CARRIERWAVE-->
        <%= image_tag '', class: 'img-fluid', alt: 'new-project-cover', data: { src: 'holder.js/1200x550' } %>
        <%= form.button t('projects.new.cover.add'), type: 'button', class: 'form-control btn btn-light' %>
      </div>
      <div class="form-group new-project-title">
        <%= form.text_field :name, class: 'form-control', placeholder: t('projects.new.title.placeholder') %>
      </div>
      <table class="form-group table new-project-budget">
        <tr>
          <td>
            <%= form.label :collected_budget, t('projects.new.budget.collected.label') %>
            <%= form.number_field :collected_budget, class: 'form-control' %>
          </td>
          <td class="form-group new-project-deadline">
            <%= form.label :finish_on, t('projects.new.deadline.label') %>
            <%= form.date_field :finish_on, class: 'form-control' %>
          </td>
          <td>
            <%= form.label :required_budget, t('projects.new.budget.estimated.label') %>
            <%= form.number_field :required_budget, class: 'form-control' %>
          </td>
        </tr>
      </table>
    </div>

    <div class="new-project-details">
      <div class="new-project-details-left">
        <div class="form-group new-project-resources">
          <%= form.label :resources, t('projects.new.resources.label') %>
          <div class="new-resource-container">
            <!--RESOURCES-->
            <%= render 'resources/new' %>
          </div>
          <%= form.button '+ ' + t('projects.new.resources.add'), class: 'btn btn-sm btn-link new-resource-add' %>
        </div>
      </div>

      <div class="form-group new-project-description">
        <%= form.label :description, t('projects.new.description.label') %>
        <%= form.text_area :description, class: 'form-control', placeholder: t('projects.new.description.placeholder'),
            rows: 10, id: 'simplemde' %>
      </div>

      <div class="new-project-details-right">
        <div class="new-project-partners">
          <%= form.label :partners, t('projects.new.partners.label') %>
          <div class="new-partner-container">
            <!--PARTNERS-->
          </div>
          <%= form.button '+ ' + t('projects.new.partners.add'), class: 'btn btn-sm btn-link new-partner-add' %>
        </div>
        <div class="new-project-ambassadors">
          <%= form.label :ambassadors, t('projects.new.ambassadors.label') %>
          <div class="new-ambassador-container">
            <!--AMBASSADORS-->
          </div>
          <%= form.button '+ ' + t('projects.new.ambassadors.add'), class: 'btn btn-sm btn-link new-ambassador-add' %>
        </div>
        <div class="new-project-team">
          <%= form.label :team, t('projects.new.team.label') %>

          <div class="new-team-member-container">
            <div class="new-team-leader">
              <%= image_tag '', class: 'rounded', alt: 'team-leader-icon', data: { src: 'holder.js/50x50' } %>
              <div>
                <%= link_to t('projects.new.team.leader.label') %>
                <strong>YOU!</strong>
              </div>
            </div>
            <!--TEAM MEMBERS-->
          </div>
          <%= form.button '+ ' + t('projects.new.team.add'), class: 'btn btn-sm btn-link new-team-member-add' %>
        </div>
      </div>
    </div>
    <%= form.submit t('projects.new.publish'), class: 'btn btn-success btn-lg btn-block form-control' %>
<% end %>

app/views/projects/show.html.erb
<div class="project-info-header">
  <h1><%= @project.name %></h1>
  <h6>
    <% @project.categories.each do |category| %>
      <%= link_to category.name, category %>
    <% end %> | <%= link_to 'Location', @project.location %>
  </h6>
</div>

<div class="project-info-grid">
  <div class="project-info-content">
    <!--LEFT SIDE CONTENT-->
    <div class="project-info-multimedia">
      <!--VIDEOS/PICS-->
      <%= image_tag '', class: 'project-cover', alt: 'project-cover', data: { src: 'holder.js/600x400' } %>
    </div>

    <div class="project-info-description">
      <%= markdown(@project.description) %>
    </div>
  </div>

  <div class="project-info-sidebar">
    <!--RIGHT SIDE CONTENT-->
    <div class="project-statistics">
      <span class="project-popularity">
        <span class="popularity-highlight">
          #<%= @project.sort_order %>
        </span> Top Growing Project
      </span>

      <div class="progress">
        <div class="progress-bar" role="progressbar"></div>
      </div>

      <h6><%= number_to_currency(@project.collected_budget) %> PLN</h6>
      <p>of <%= number_to_currency(@project.required_budget) %>PLN goal</p>
      <p><!-- TO BE IMPLEMENTED %--> <%= rand 100 %> people backed this up</p>
    </div>

    <div class="project-actions">
      <button class="btn btn-lg btn-success">BACK THIS PROJECT</button>
      <button class="btn btn-lg btn-outline-success">+ NEED: IT SKILLS</button>
      <button class="btn btn-lg btn-outline-success">+ NEED: MEETING PLACE</button>
      <%= link_to 'And 2 more...' %>
    </div>

    <div class="project-backer-info">
      2 People and 1 Organisation helped with their resources.
      <%= link_to "What's that about?" %>
    </div>

    <div class="project-social-info">
      <!--TO BE IMPLEMENTED-->
      <button class="btn btn-lg btn-primary">SHARE TO HELP!</button>
      <%= link_to '', class: 'btn btn-lg btn-link' do %>
          Friend and <%= rand 10 %> others shared or liked it
      <% end %>
      <span>
        <% 10.times do %>
          <%= image_tag '', class: 'rounded', alt: 'social-interaction-icon', data: { src: 'holder.js/40x40' } %>
        <% end %>
      </span>
    </div>

    <div class="project-executives">
      <section class="project-sponsors">
        <p>SPONSORS</p>
        <button class="btn btn-lg">
          <%= image_tag '', class: 'rounded', alt: 'executive-sponsor-icon', data: { src: 'holder.js/140x70' } %>
        </button>
      </section>

      <section class="project-team">
        <p>PROJECT TEAM</p>
        <button class="btn btn-lg project-team-leader">
          <%= image_tag '', class: 'rounded', alt: 'team-leader-icon', data: { src: 'holder.js/50x50' } %>
          Leader Megatron
        </button>
        <div class="btn btn-lg project-team-members">
          <span>
            <% 10.times do %>
              <%= image_tag '', class: 'rounded', alt: 'team-member-icon', data: { src: 'holder.js/40x40' } %>
            <% end %>
          </span>
        </div>
      </section>
    </div>

    <div class="report-project">
      <%= link_to '', class: 'btn btn-lg btn-link' do %>
          <%= image_tag '', class: '', alt: 'report-project-icon', data: { src: 'holder.js/35x35' } %>
          REPORT THIS PROJECT
      <% end %>
    </div>
  </div>
</div>